FEAT: adjust flex direction
lifeomic/chromicons.com pull request #65
Opened 2021-06-29 14:48 UTC by ghgamble

2021-06-29 14:52 UTC, ynotdraw requested changes

2021-06-29 14:52 UTC, ynotdraw commented on src/pages/index.js
> +        <div className="flex justify-between items-start shadow-banner px-4 lg:flex-row sm:flex-col sm:px-6 lg:px-6 bg-white flex-col sm:flex-row">
Looks like you have two conflicting styles here. There are two setting the flex direction sm:flex-col and on the end now sm:flex-row

2021-06-29 15:05 UTC, ynotdraw commented
Should the search field be full width as well when on mobile?  There's a `w-full` class you can use if so.

2021-06-30 17:15 UTC, dexterca commented
I just pulled this down and SearchField is still not full width on mobile. I troubleshot this myself and found it incredibly difficult to fix (probably b/c I'm a Tailwind noob) but I think I have a fix now. @ghgamble let me know if you want to try fixing yourself or if you want me to commit my fix to this PR.

<img width="624" alt="Screen Shot 2021-06-30 at 1 11 10 PM" src="https://user-images.githubusercontent.com/485903/124003348-d36e0980-d9a4-11eb-8c2c-16490ffc4424.png">

2021-06-30 19:17 UTC, ghgamble commented
That's fine with me.. I struggled to find a fix too. If you want to push it to this branch/PR. Thanks!

2021-06-30 19:38 UTC, ghgamble commented
Casey was able to make a fix.

2021-06-30 20:13 UTC, ynotdraw approved these changes

2021-06-30 20:14 UTC, merged